variables:
    BUNDLE: "roger-dev.flatpak"

stages:
   - build

flatpak:
    image: registry.gitlab.com/alatiera/flatpak-docker-images/gnome:3.28
    stage: build
    variables:
        MANIFEST_PATH: "platform/linux/org.tabos.roger.flatpak.json"
        MESON_ARGS: ""
        FLATPAK_MODULE: "roger"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        DBUS_ID: "org.tabos.RogerDevel"

    script:
        - flatpak-builder --stop-at=${FLATPAK_MODULE} app ${MANIFEST_PATH}
        # Make sure to keep this in sync with the Flatpak manifest, all arguments
        # are passed except the config-args because we build it ourselves
        - flatpak build app meson --prefix=/app ${MESON_ARGS} _build
        - flatpak build app ninja -C _build install
        - flatpak-builder --finish-only --repo=repo app ${MANIFEST_PATH}
        # Generate a Flatpak bundle
        - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} ${DBUS_ID}
        # Run automatic tests inside the Flatpak env
        - flatpak build app ninja -C _build test
    artifacts:
        paths:
            - ${BUNDLE}
            - _build/meson-logs/meson-log.txt
            - _build/meson-logs/testlog.txt
        expire_in: 30 days
    cache:
        paths:
            - .flatpak-builder/cache
