#!/bin/bash

# redirect all output to stdout and stderr to /tmp/roger.log
exec >/tmp/roger.log 2>&1

install_path=$2/RogerRouter.app

echo roger postinstall script, trying to install printer
echo install_path = ${install_path}

echo "Executing: lpadmin  -p Roger-Router-Fax -P ${install_path}/Contents/Resources/share/roger/roger-fax.ppd -v socket://localhost:9100/ -E"
lpadmin -p Roger-Router-Fax -P "${install_path}/Contents/Resources/share/roger/roger-fax.ppd" -v socket://localhost:9100/ -E
retval=$?
if test $retval != 0; then
	echo lpadmin command failed, returned $retval
else
	echo Printer Roger-Router-Fax is added
fi
exit $retval
