#!/bin/bash

# redirect all output to stdout and stderr to /tmp/roger.log
exec >/tmp/roger.log 2>&1

install_path=$2/roger.app

echo install_path = ${install_path} 

lpadmin -x Roger-Router-Fax -E
retval=$?
rm -rf /var/spool/roger/

if test $retval != 0; then
	echo lpadmin command failed, returned $retval
else
	echo Printer Roger-Router-Fax is added
fi
exit $retval
