#!/bin/bash

# redirect all output to stdout and stderr to /tmp/roger.log
exec >/tmp/roger.log 2>&1

install_path=$2/roger.app

echo roger postinstall script, trying to install printer
echo install_path = ${install_path} 

# Keep this code here - if glib supports notify on os x we can switch to spooler version
#mkdir -p /var/spool/roger
#chown root:_lpadmin /var/spool/roger
#chmod 2770 /var/spool/roger/
#cp ${install_path}/Contents/Resources/share/roger/roger-cups /usr/libexec/cups/backend/
#chmod 700 /usr/libexec/cups/backend/roger-cups
#chown root:wheel /usr/libexec/cups/backend/roger-cups
#lpadmin -p Roger-Router-Fax -E -v roger-cups:/ -P ${install_path}/Contents/Resources/share/roger/roger-fax.ppd

lpadmin  -p Roger-Router-Fax -P ${install_path}/Contents/Resources/share/roger/roger-fax.ppd -v socket://localhost:9100/ -E
retval=$?
if test $retval != 0; then
	echo lpadmin command failed, returned $retval
else
	echo Printer Roger-Router-Fax is added
fi
exit 0
#exit $retval
